Add functional scripts

diff --git a/root/opt/scripts/deploy-task b/root/opt/scripts/deploy-task
--- a/root/opt/scripts/deploy-task
+++ b/root/opt/scripts/deploy-task
@@ -1,11 +1,109 @@
 #!/bin/bash
 
+if [ ! -e /winattacklab ]; then
+    echo "=========================="
+    echo "executing /opt/scripts/deploy-task"
+    echo "No content found."
+    exit 0
+fi
+
+source /winattacklab/.deploy
+source /winattacklab/proxy.env
+
 cd /winattacklab/
 
-echo "=========================="
-echo "executing /opt/scripts/deploy-task"
+echo "$(date): Deployment Manager Version 2021-04-16-R104"
+sleep 2
 
+echo "$(date): terraform deploy button clicked" >>/winattacklab/logs/terraform-deploy.log
 
+case "$DEPLOYED" in
+init)
+    if [ -e /winattacklab/plan.fail ]; then
+        echo "$(date): Failed to create terraform plan."
+        echo "$(date): Opening plan log"
+        sleep 2
+        cat /winattacklab/logs/terraform-plan.log
+        exit 1
+    fi
 
+    echo "DEPLOYED=\"deploying\"" >/winattacklab/.deploy
+    echo "DESTROYED=\"init\"" >/winattacklab/.destroy
+    echo "$(date): terraform apply --auto-approve"
+    echo "$(date): terraform apply --auto-approve started" >>/winattacklab/logs/terraform-deploy.log
+    echo "$(date): terraform apply log" >>/winattacklab/logs/terraform-deploy.log
+    echo "$(date): terraform deploy has been executed on $(date)" >/tmp/start-date.log
+    echo "$(date): please click on the \"Log\" menu to see the deploy log file"
 
+    START=$(date +%s)
+    # 24h
+    # DUR=68400
 
+    # 2h (testing)
+    DUR=43200
+    END=$((START + DUR))
+    echo $START >/winattacklab/terraform.start
+    echo $END >/winattacklab/terraform.end
+    echo "$(date): infrastructure will run until: $(date -d @$((START + DUR)))"
+
+    screen -d -m -t deploy-task-background /opt/scripts/deploy-task-background &
+    echo "$(date): terraform apply has been executed" >>/winattacklab/logs/terraform-deploy.log
+    echo "$(date): terraform apply has been executed"
+    ;;
+
+deploying)
+    ps -ef | grep "/usr/bin/terraform apply" | grep -v grep >/dev/null
+    RESULT=$?
+    if [ $RESULT -eq 0 ]; then
+        echo "$(date): terraform apply is still running"
+        echo "$(date): terraform apply is still running" >>/winattacklab/logs/terraform-deploy.log
+    else
+        echo "$(date): terraform apply job has finished"
+        echo "$(date): terraform apply job has finished" >>/winattacklab/logs/terraform-deploy.log
+        terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-deploy.log
+        R1=$?
+        if [ $R1 -eq 0 ]; then
+            echo "$(date): deploy was successful: infrastructure running"
+            echo "$(date): deploy was successful: infrastructure running" >>/winattacklab/logs/terraform-deploy.log
+        else
+            echo "$(date): infrastructure is not yet up and running"
+            echo "$(date): infrastructure is not yet up and running" >>/winattacklab/logs/terraform-deploy.log
+        fi
+
+    fi
+
+    echo "====== Azure Resource Group ====="
+    terraform state show 'azurerm_resource_group.winattacklabgroup' | grep id | cut -d'/' -f5- | cut -d '"' -f1
+    echo "================================="
+    sleep 3
+
+    echo "$(date): opening log"
+    sleep 5
+    tail -n +0 -f /winattacklab/logs/terraform-deploy.log
+    ;;
+
+finished)
+    echo "====== auto deploy ====="
+    echo "$(date): terraform deploy has been finished"
+    echo "$(date): terraform deploy has been finished" >>/winattacklab/logs/terraform-deploy.log
+
+    echo "====== Azure Resource Group ====="
+    terraform state show 'azurerm_resource_group.winattacklabgroup' | grep id | cut -d'/' -f5- | cut -d '"' -f1
+    echo "================================="
+    sleep 3
+
+    if [ -e /winattacklab/terraform.end ]; then
+        /opt/scripts/show-when-cron-will-destroy-infrastructure
+    fi
+
+    echo "$(date): opening deploy log"
+    sleep 5
+    cat /winattacklab/logs/terraform-deploy.log
+    echo "$(date): terraform deploy has been finished"
+    ;;
+
+*)
+    exit 1
+    ;;
+
+esac
diff --git a/root/opt/scripts/destroy b/root/opt/scripts/destroy
--- a/root/opt/scripts/destroy
+++ b/root/opt/scripts/destroy
@@ -1,11 +1,130 @@
 #!/bin/bash
 
+if [ ! -e /winattacklab ]; then
+    echo "=========================="
+    echo "executing /opt/scripts/destroy"
+    echo "No content found."
+    exit 0
+fi
+
+source /winattacklab/.deploy
+source /winattacklab/.destroy
+source /winattacklab/proxy.env
+
 cd /winattacklab/
 
-echo "=========================="
-echo "executing /opt/scripts/destroy"
+case "$DEPLOYED" in
+init)
+    echo "$(date): terraform deploy not yet started" >>/winattacklab/logs/terraform-destroy.log
+    echo "$(date): terraform deploy not yet started"
+    if [ -e /winattacklab/plan.fail ]; then
+        echo "$(date): Failed to create terraform plan."
+        echo "$(date): Opening plan log"
+        sleep 2
+        cat /winattacklab/logs/terraform-plan.log
+        exit 1
+    else
+        echo "$(date): if you want to deploy, click on \"Run Task\" in the Deploy menu"
+    fi
+    ;;
 
+deploying)
+    ps -ef | grep "/usr/bin/terraform apply" | grep -v grep >/dev/null
+    RESULT=$?
+    if [ $RESULT -eq 0 ]; then
+        echo "$(date): terraform apply is running" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): terraform apply is running"
+        cat /tmp/start-date.log
+        echo "$(date): please wait until the infrastructure is fully deployed"
+        echo "$(date): you must wait until the infrastructure is fully deployed before you can destroy it"
+        echo "$(date): click on \"Run Task\" in the Log menu to see the deploy log"
+    else
+        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..." >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..."
 
+        terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-destroy.log
+        R1=$?
+        if [ $R1 -eq 0 ]; then
+            echo "$(date): deploy was successful: infrastructure running" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): deploy was successful: infrastructure running"
+            echo "DEPLOYED=\"finished\"" >/winattacklab/.deploy
 
+            if [ -e /winattacklab/terraform.end ]; then
+                /opt/scripts/show-when-cron-will-destroy-infrastructure
+            fi
 
+        else
+            echo "$(date): deploy error: infrastructure not running" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): deploy error: infrastructure not running"
+        fi
 
+    fi
+
+    ;;
+
+finished)
+    case "$DESTROYED" in
+    init)
+        echo "$(date): terraform is fully deployed" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): terraform is fully deployed"
+        echo "$(date): user did not click on destroy" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): user did not click on destroy"
+
+        echo "====== Azure Resource Group ====="
+        terraform state show 'azurerm_resource_group.winattacklabgroup' | grep id | cut -d'/' -f5- | cut -d '"' -f1
+
+        if [ -e /winattacklab/terraform.end ]; then
+            /opt/scripts/show-when-cron-will-destroy-infrastructure
+        fi
+
+        echo "================================="
+        echo "$(date): click on \"Run Task\" in the Ip Addresses menu to get the login credentials"
+        echo "================================="
+
+        ;;
+
+    running)
+        ps -ef | grep "/usr/bin/terraform destroy" | grep -v grep >/dev/null
+        RESULT=$?
+        if [ $RESULT -eq 0 ]; then
+            echo "$(date): user clicked on the destroy button" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): user clicked on the destroy button"
+            echo "$(date): terraform destroy has started" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): terraform destroy has started"
+        else
+            echo "$(date): user clicked on the destroy button" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): user clicked on the destroy button"
+
+            terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-destroy.log
+            R1=$?
+            if [ $R1 -eq 0 ]; then
+                echo "$(date): destroy not finished yet: infrastructure still destroying" >>/winattacklab/logs/terraform-destroy.log
+                echo "$(date): destroy not finished yet: infrastructure still destroying"
+                echo "$(date): click on \"Run Task\" in the Log menu to see the destroy log"
+            else
+                echo "$(date): infrastructure is fully down" >>/winattacklab/logs/terraform-destroy.log
+                echo "$(date): infrastructure is fully down"
+                echo "DESTROYED=\"finished\"" >/winattacklab/.destroy
+                echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+            fi
+
+        fi
+        ;;
+
+    finished)
+        echo "$(date): destroy successfully finished - will reset deployment to init" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): destroy successfully finished - will reset deployment to init"
+        echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+        echo "DESTROYED=\"init\"" >/winattacklab/.destroy
+        ;;
+    *)
+        exit 1
+        ;;
+    esac
+    ;;
+
+*)
+    exit 1
+    ;;
+
+esac
diff --git a/root/opt/scripts/destroy-task b/root/opt/scripts/destroy-task
--- a/root/opt/scripts/destroy-task
+++ b/root/opt/scripts/destroy-task
@@ -1,11 +1,123 @@
 #!/bin/bash
 
+if [ ! -e /winattacklab ]; then
+    echo "=========================="
+    echo "executing /opt/scripts/destroy-task"
+    echo "No content found."
+    exit 0
+fi
+
+source /winattacklab/.deploy
+source /winattacklab/.destroy
+source /winattacklab/proxy.env
+
 cd /winattacklab/
 
-echo "=========================="
-echo "executing /opt/scripts/destroy-task"
+echo "$(date): Deployment Manager Version 2021-04-16-R104"
+sleep 2
 
+case "$DEPLOYED" in
+init)
+    echo "$(date): terraform deploy not yet started - cannot destroy"
+    echo "$(date): terraform deploy not yet started - cannot destroy" >>/winattacklab/logs/terraform-destroy.log
+    ;;
 
+deploying)
+    echo "$(date): terraform deploy currently running - stopping it"
+    echo "$(date): terraform deploy currently running - stopping it" >>/winattacklab/logs/terraform-destroy.log
+    pkill terraform
 
+    echo "====== Azure Resource Group ====="
+    terraform state show 'azurerm_resource_group.winattacklabgroup' | grep id | cut -d'/' -f5- | cut -d '"' -f1
+    echo "================================="
+    ;&
 
+deploying | finished)
+    echo "$(date): terraform deployment will now be destroyed"
+    echo "$(date): terraform deployment will now be destroyed" >>/winattacklab/logs/terraform-destroy.log
 
+    case "$DESTROYED" in
+    init)
+        rm /winattacklab/terraform.start
+        rm /winattacklab/terraform.end
+        echo "$(date): destroy clicked in DM Web UI" >>/tmp/terraform.destroy.cron
+        echo "$(date): terraform deploy has been executed on $(date)" >/tmp/start-stop.log
+
+        echo "DESTROYED=\"running\"" >/winattacklab/.destroy
+        echo "$(date): az group delete started" >>/winattacklab/logs/terraform-status.log
+        echo "$(date): az group delete started" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): az group delete started" >>/winattacklab/logs/terraform-destroy.log
+        /opt/scripts/az-delete
+        if [ $? -ne 0 ]; then
+            echo "$(date): Unable to destroy via Azure CLI. Falling back to terraform." >>/winattacklab/logs/terraform-status.log
+            echo "$(date): Unable to destroy via Azure CLI. Falling back to terraform." >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): terraform destroy log" >>/winattacklab/logs/terraform-destroy.log
+
+            echo "terraform destroy --auto-approve"
+            echo "$(date): terraform destroy --auto-approve started" >>/winattacklab/logs/terraform-status.log
+            echo "$(date): terraform destroy --auto-approve started" >>/winattacklab/logs/terraform-destroy.log
+            echo "$(date): terraform destroy log" >>/winattacklab/logs/terraform-destroy.log
+            screen -d -m -t destroy-task-background /opt/scripts/destroy-task-background &
+            echo "$(date): terraform destroy --auto-approve finished" >>/winattacklab/logs/terraform-status.log
+            echo "$(date): please click on the \"Log\" menu to see the destroy log"
+        else
+            echo "DESTROYED=\"finished\"" >/winattacklab/.destroy
+            echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+        fi
+        ;;
+    running)
+        ps -ef | grep "/usr/bin/terraform destroy" | grep -v grep >/dev/null
+        RESULT=$?
+        if [ $RESULT -eq 0 ]; then
+            echo "$(date): terraform destroy is still running"
+            echo "$(date): terraform destroy was executed on: $(cat /tmp/start-stop.log)"
+            echo "$(date): terraform destroy is still running" >>/winattacklab/logs/terraform-destroy.log
+        else
+            echo "$(date): terraform destroy was executed on: $(cat /tmp/start-stop.log) but not finished yet"
+            echo "$(date): terraform destroy was executed on: $(cat /tmp/start-stop.log) but not finished yet" >>/winattacklab/logs/terraform-destroy.log
+            terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-destroy.log
+            R1=$?
+            if [ $R1 -eq 0 ]; then
+                echo "$(date): destroy was not yet successul: infrastructure still running"
+                echo "$(date): destroy was not yet successul: infrastructure still running" >>/winattacklab/logs/terraform-destroy.log
+                echo "$(date): running terraform destroy again" >>/winattacklab/logs/terraform-destroy.log
+                screen -d -m -t destroy-task-background /opt/scripts/destroy-task-background &
+            else
+                echo "$(date): infrastructure is fully down"
+                echo "$(date): infrastructure is fully down" >>/winattacklab/logs/terraform-destroy.log
+                echo "DESTROYED=\"finished\"" >/winattacklab/.destroy
+                echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+            fi
+
+        fi
+
+        echo "$(date): opening destroy logs"
+        sleep 5
+        echo "===== Azure Delete Log ====="
+        tail -500 /winattacklab/logs/az.log
+        echo "===== Terraform Destroy Log ====="
+        tail -500 /winattacklab/logs/terraform-destroy.log
+        ;;
+    finished)
+        echo "$(date): terraform destroy was executed on: $(cat /tmp/start-stop.log)"
+        echo "terraform destroy has been finished"
+        echo "terraform destroy has been finished" >>/winattacklab/logs/terraform-destroy.log
+        echo "$(date): opening destroy logs"
+        sleep 5
+
+        echo "===== Azure Delete Log ====="
+        tail -500 /winattacklab/logs/az.log
+        echo "===== Terraform Destroy Log ====="
+        tail -500 /winattacklab/logs/terraform-destroy.log
+        echo "terraform destroy has been finished"
+        ;;
+    *)
+        exit 1
+        ;;
+    esac
+    ;;
+
+*)
+    exit 1
+    ;;
+esac
diff --git a/root/opt/scripts/ipaddresses-task b/root/opt/scripts/ipaddresses-task
--- a/root/opt/scripts/ipaddresses-task
+++ b/root/opt/scripts/ipaddresses-task
@@ -1,11 +1,125 @@
 #!/bin/bash
 
+if [ ! -e /winattacklab ]; then
+    echo "=========================="
+    echo "executing /opt/scripts/ipaddresses-task"
+    echo "No content found."
+    exit 0
+fi
+
+source /winattacklab/.deploy
+source /winattacklab/.destroy
+source /winattacklab/proxy.env
+
 cd /winattacklab/
 
-echo "=========================="
-echo "executing /opt/scripts/ipaddresses-task"
+case "$DEPLOYED" in
+init)
+    echo "$(date): terraform deploy not yet started" >>/winattacklab/logs/terraform-ipaddresses.log
+    echo "$(date): terraform deploy not yet started"
+    echo "$(date): if you want to deploy, click on \"Run Task\" in the Deploy menu"
+    ;;
 
+deploying)
+    ps -ef | grep "/usr/bin/terraform apply" | grep -v grep >/dev/null
+    RESULT=$?
+    if [ $RESULT -eq 0 ]; then
+        echo "$(date): terraform apply is running" >>/winattacklab/logs/terraform-ipaddresses.log
+        echo "$(date): terraform apply is running"
+        echo "$(date): please wait until the infrastructure is fully deployed"
+    else
+        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..." >>/winattacklab/logs/terraform-ipaddresses.log
+        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..."
 
+        terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-ipaddresses.log
+        R1=$?
+        if [ $R1 -eq 0 ]; then
+            echo "$(date): deploy was successful: infrastructure running" >>/winattacklab/logs/terraform-ipaddresses.log
+            echo "$(date): deploy was successful: infrastructure running"
+            echo "DEPLOYED=\"finished\"" >/winattacklab/.deploy
+            terraform output -no-color 2>&1 | tee -a /winattacklab/logs/terraform-ipaddresses.log
 
+            if [ -e /winattacklab/terraform.end ]; then
+                /opt/scripts/show-when-cron-will-destroy-infrastructure
+            fi
 
+            if [ -e /opt/scripts/show-credentials.sh ]; then
+                /opt/scripts/show-credentials.sh
+            fi
 
+        else
+
+            echo "$(date): deploy error: infrastructure not running" >>/winattacklab/logs/terraform-ipaddresses.log
+            echo "$(date): deploy error: infrastructure not running"
+        fi
+
+    fi
+
+    ;;
+
+finished)
+    case "$DESTROYED" in
+    init)
+        echo "$(date): terraform is fully deployed" >>/winattacklab/logs/terraform-ipaddresses.log
+        echo "$(date): terraform is fully deployed"
+        echo "$(date): user did not click on destroy" >>/winattacklab/logs/terraform-ipaddresses.log
+        echo "$(date): user did not click on destroy"
+        echo "====== Azure Resource Group ====="
+        terraform state show 'azurerm_resource_group.winattacklabgroup' | grep id | cut -d'/' -f5- | cut -d '"' -f1
+        echo "================================="
+
+        terraform output -no-color 2>&1 | tee -a /winattacklab/logs/terraform-ipaddresses.log
+
+        if [ -e /winattacklab/terraform.end ]; then
+            /opt/scripts/show-when-cron-will-destroy-infrastructure
+        fi
+
+        if [ -e /opt/scripts/show-credentials.sh ]; then
+            /opt/scripts/show-credentials.sh
+        fi
+
+        ;;
+    running)
+        ps -ef | grep "/usr/bin/terraform destroy" | grep -v grep >/dev/null
+        RESULT=$?
+        if [ $RESULT -eq 0 ]; then
+            echo "$(date): user clicked on the destroy button" >>/winattacklab/logs/terraform-ipaddresses.log
+            echo "$(date): user clicked on the destroy button"
+            echo "$(date): terraform destroy has started" >>/winattacklab/logs/terraform-ipaddresses.log
+            echo "$(date): terraform destroy has started"
+        else
+            echo "$(date): user clicked on the destroy button" >>/winattacklab/logs/terraform-ipaddresses.log
+            echo "$(date): user clicked on the destroy button"
+
+            terraform state show 'azurerm_resource_group.winattacklabgroup' >>/winattacklab/logs/terraform-ipaddresses.log
+            R1=$?
+            if [ $R1 -eq 0 ]; then
+                echo "$(date): destroy not finished yet: infrastructure still running" >>/winattacklab/logs/terraform-ipaddresses.log
+                echo "$(date): destroy not finished yet: infrastructure still running"
+            else
+                echo "$(date): infrastructure is fully down" >>/winattacklab/logs/terraform-ipaddresses.log
+                echo "$(date): infrastructure is fully down"
+                echo "DESTROYED=\"finished\"" >/winattacklab/.destroy
+                echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+            fi
+
+        fi
+        ;;
+
+    finished)
+        echo "$(date): destroy successfully finished - will reset deployment to init" >>/winattacklab/logs/terraform-ipaddresses.log
+        echo "$(date): destroy successfully finished - will reset deployment to init"
+        echo "DEPLOYED=\"init\"" >/winattacklab/.deploy
+        echo "DESTROYED=\"init\"" >/winattacklab/.destroy
+        ;;
+    *)
+        exit 1
+        ;;
+    esac
+    ;;
+
+*)
+    exit 1
+    ;;
+
+esac
