Print info if resource group variable name cannot be read

diff --git a/root/opt/scripts/deploy-task b/root/opt/scripts/deploy-task
--- a/root/opt/scripts/deploy-task
+++ b/root/opt/scripts/deploy-task
@@ -18,7 +18,12 @@ sleep 2
 echo "$(date): terraform deploy button clicked" >>/winattacklab/logs/terraform-deploy.log
 
 resource_group_name=`grep -re "^resource \"azurerm_resource_group\"" *.tf | awk -F"\"" '{print $4}'`
-echo "Resource group variable name: $resource_group_name."
+if [ $? -eq 0 ]; then
+    echo "$(date): Resource group variable name is '$resource_group_name.'" >> /winattacklab/logs/terraform-deploy.log
+else
+    echo "$(date): Unable to determine resource group variable name" >> /winattacklab/logs/terraform-deploy.log
+    echo "$(date): Unable to determine resource group variable name"
+fi
 
 case "$DEPLOYED" in
 init)
diff --git a/root/opt/scripts/destroy-task-background b/root/opt/scripts/destroy-task-background
--- a/root/opt/scripts/destroy-task-background
+++ b/root/opt/scripts/destroy-task-background
@@ -10,7 +10,12 @@ echo "`date`: Deployment Manager Version 2021-04-16-R104"
 sleep 2
 
 resource_group_name=`grep -re "^resource \"azurerm_resource_group\"" *.tf | awk -F"\"" '{print $4}'`
-echo "Resource group variable name: $resource_group_name."
+if [ $? -eq 0 ]; then
+    echo "$(date): Resource group variable name is '$resource_group_name.'" >> /winattacklab/logs/terraform-destroy.log
+else
+    echo "$(date): Unable to determine resource group variable name" >> /winattacklab/logs/terraform-destroy.log
+    echo "$(date): Unable to determine resource group variable name"
+fi
 
 case "$DEPLOYED" in
         init)
